"use strict";

export const EQUAL_TO_JSON_COMPARISON = 0;
export const NOT_EQUAL_TO_JSON_COMPARISON = Infinity;
export const STRICTLY_LESS_THAN_JSON_COMPARISON = 1;

export default {
  EQUAL_TO_JSON_COMPARISON,
  NOT_EQUAL_TO_JSON_COMPARISON,
  STRICTLY_LESS_THAN_JSON_COMPARISON
};
