"use strict";

export const MAJOR_VERSION_NUMBER_CHANGE = Infinity;
export const MINOR_VERSION_NUMBER_CHANGE = 1;
export const PATCH_VERSION_NUMBER_CHANGE = 0;

export default {
  MAJOR_VERSION_NUMBER_CHANGE,
  MINOR_VERSION_NUMBER_CHANGE,
  PATCH_VERSION_NUMBER_CHANGE
};
